name: Build and Test WPF App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: msbuild WpfAppLauncher.sln /t:Restore

    - name: Build project
      run: msbuild WpfAppLauncher.sln /p:Configuration=Release

    - name: Run tests
      run: dotnet test WpfAppLauncher.Tests/WpfAppLauncher.Tests.csproj --no-build --verbosity normal
